name: Validate Test Tool meta data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Validate metadata
        run: |
          pip install -U solar-registry
          solar-registry validate unittest