name: Validate Test Tool meta data

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      - name: Validate metadata
        run: |
          uvx --from 'solar-registry' solar-registry validate python_unittest
