# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh
      - name: Build package
        run: |
          cd python_unittest
          uvx --from build pyproject-build --installer uv
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: python_unittest/dist/
          skip-existing: true
      - name: Release metadata
        run: |
          git config --global user.name 'asiazhang'
          git config --global user.email 'asiazhang2002@gmail.com'
          pip install -U solar-registry
          solar-registry pull-request python_unittest
        env:
          GH_TOKEN: ${{ secrets.TESTSOLAR_TOKEN }}

